// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfrbgmlszfsmbibzethj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmcmJnbWxzemZzbWJpYnpldGhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MDMxNjMsImV4cCI6MjA1OTA3OTE2M30.HQnL2y78fCbiA8JxemalFn3w_Oor7iff4qvuTazRJbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);